# Generated by Django 6.0.5 on 2026-06-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bulletin_alter_fish_id_alter_fishdelivery_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('retailer', 'Retailer'), ('staff', 'Staff'), ('guest', 'Guest/Consumer')], max_length=20),
        ),
    ]
