# Generated by Django 6.0.5 on 2026-06-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_retailer_latitude_retailer_longitude_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('retailer', 'Retailer'), ('staff', 'Staff'), ('guest', 'Guest/Consumer'), ('supplier', 'Supplier/Vessel Owner')], max_length=20),
        ),
    ]
