# Generated by Django 6.0.5 on 2026-06-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishprice',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
