# Generated by Django 5.2.8 on 2026-06-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fishprice_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplysource',
            name='supplier_type',
            field=models.CharField(choices=[('vessel', 'Fishing Vessel'), ('external', 'External Supplier')], default='vessel', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplysource',
            name='boat_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplysource',
            name='status',
            field=models.CharField(choices=[('at_sea', 'At Sea'), ('in_transit', 'In Transit'), ('docked', 'Docked'), ('arrived', 'Arrived')], default='at_sea', max_length=20),
        ),
    ]
