# Generated by Django 6.0.5 on 2026-06-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_historicalaccountapplication_historicalfishdelivery_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fishdelivery',
            index=models.Index(fields=['delivery_date', 'fish', 'delivery_status'], name='api_fishdel_deliver_ab57ea_idx'),
        ),
        migrations.AddIndex(
            model_name='fishdelivery',
            index=models.Index(fields=['delivery_date'], name='api_fishdel_deliver_afb652_idx'),
        ),
        migrations.AddIndex(
            model_name='fishdelivery',
            index=models.Index(fields=['retailer', 'fish'], name='api_fishdel_retaile_826fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='fishprice',
            index=models.Index(fields=['market_date', 'fish'], name='api_fishpri_market__707cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='fishprice',
            index=models.Index(fields=['market_date'], name='api_fishpri_market__cf0375_idx'),
        ),
        migrations.AddIndex(
            model_name='fishprice',
            index=models.Index(fields=['retailer', 'fish'], name='api_fishpri_retaile_5b1a24_idx'),
        ),
    ]
