# Generated by Django 6.0.5 on 2026-09-05 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_fishdelivery_api_fishdel_deliver_ab57ea_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplysource',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vessel', to=settings.AUTH_USER_MODEL),
        ),
    ]
